### PR TITLE
Add support for detecting NSIS

### PR DESCRIPTION
**Pull request by SilasLaspada**

### CODE REVIEW

**Comment by claunia** [comment]
When did an opensource installer system become a copy protection?

**Comment by Whovian9369** [comment]
I'd say it's more of a note there of "Need more info" so we can check *if* there's more to be looked at there, etc

**Comment by claunia** [comment]
Still looks incorrect, it is added as a copy protection, both in code and in documentation.

Are we going to consider ARJ, ARK, ARC, ZOO, PAK, ZIP, GZ, DEB, RPM, CPIO, et al, to be copy protections now?

**Comment by SilasLaspada** [comment]
I’m just following the way the rest of the code does it for now, other things like UPX are also detected as copy protections so it would need a separate PR to deal with all that.

**Comment by mnadareski** [comment]
Packers are protections for now. This will be addressed later.

**Review by mnadareski — APPROVED** [review]
I'll fix the formatting later

**Pull request merged**
